### ISSUE TITLE
Installation on Digital Ocean Droplet

### ISSUE THREAD

**Issue by raphael-evolutap** [RocketChat/Rocket.Chat.Metrics#1]
I'm trying to install on Rocket.Chat droplet from Digital Ocean Marketplace, but it not working.

Installation works fine, i have to change port to 3300 in docker file, because Rocket.Chat is alreading using port 3000.

But after install and up i'm not able to access,  http://${HOST_IP}:3300 or http://${HOST_DOMAIN}:3300 doesnt work.

Thanks

**Comment by frdmn** [comment]
Hi @raphael-evolutap 

Can you check if the containers are all properly started? What's the output of:

```shell
docker-compose ps
netstat -tulpn
```

**Comment by raphael-evolutap** [comment]
**docker-compose ps**
a4cc1ffd4823_a4cc1ffd4823_rocketchatmet   /run.sh                          Up      3000/tcp, 0.0.0.0:3300->3300/tcprics_grafana_1
rocketchatmetrics_prometheus_1            /bin/prometheus --config.f ...   Up      9090/tcp

--a4cc1ffd4823_a4cc1ffd4823_rocketch   /run.sh                          Up           3000/tcp, 0.0.0.0:3300->3300/tcpatmetrics_grafana_1
rocketchatmetrics_prometheus_1       /bin/prometheus --config.f ...   Restarting
after up, prometheus is restarting.

**netstat -tulpn**
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.1:42805         0.0.0.0:*               LISTEN      3321/containerd
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN      707/systemd-resolve
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      910/sshd
tcp        0      0 127.0.0.1:3000          0.0.0.0:*               LISTEN      1007/node
tcp        0      0 127.0.0.1:27017         0.0.0.0:*               LISTEN      937/mongod
tcp6       0      0 :::80                   :::*                    LISTEN      27961/traefik
tcp6       0      0 :::22                   :::*                    LISTEN      910/sshd
tcp6       0      0 :::443                  :::*                    LISTEN      27961/traefik
tcp6       0      0 :::3300                 :::*                    LISTEN      13684/docker-proxy
udp        0      0 127.0.0.53:53           0.0.0.0:*                           707/systemd-resolv

thanks @frdmn

**Comment by frdmn** [comment]
The output of `docker-compose ps` is mushed for some reason. As you can see in the `netstat` output, nothing is running on port 3300 (which should be your Grafana container).

Check the logfiles of the containre why it's not starting properly: `docker-compose logs -f grafana`.

**Comment by raphael-evolutap** [comment]
Maybe my ports configuration in docker-compose.yml was wrong, i'm change it to 3300:3000 and now it's working.

What is credentials to login? Do i have to take extra steps? 

Thanks

**Comment by frdmn** [comment]
Great to hear that! 

You can use Grafanas default credentials to login initially: `admin`/`admin`. Forgot to add that to the docs - thanks for the hint 😊

**Comment by raphael-evolutap** [comment]
thanks man @frdmn
