### ISSUE TITLE
not collect data 

### ISSUE THREAD

**Issue by lbouquinUniv** [RocketChat/Rocket.Chat.Metrics#4]
Hi, 

I use rocketchat in a docker environment. I try to get statistic but port 9458 ha no corresponding in rocketchat. 
Why 9458 port ?

**Comment by frdmn** [comment]
Hi @lbouquinUniv! You need to enable the Prometheus exporter first - the port is also configurable within Rocket.Chat. You can adjust it your Rocket.Chat admin UI → Logs → Prometheus-

Check if it's enabled and if you also exposed the port in your Docker setup.

**Comment by lbouquinUniv** [comment]
Thanks.

**Comment by Atomzwieback** [comment]
This should be added in the Docs from https://github.com/RocketChat/Rocket.Chat.Metrics
Because i didnt know this and im was not able to track down why prometheus was not working.

**Comment by frdmn** [comment]
Added info in the README.md: https://github.com/RocketChat/Rocket.Chat.Metrics#rocketchat

**Comment by olegsidokhmetov** [comment]
> 
> 
> Hi @lbouquinUniv! You need to enable the Prometheus exporter first - the port is also configurable within Rocket.Chat. You can adjust it your Rocket.Chat admin UI → Logs → Prometheus.
> 
> Check if it's enabled and if you also exposed the port in your Docker setup.

Hello!

How I can enable port from console?

**Comment by frdmn** [comment]
Hi @olegsidokhmetov! You can enable the port from within the application itself (Rocket.Chat admin UI).

Message me [on our open instance](https://open.rocket.chat/direct/frdmn) in case you still have issues with this.
