### ISSUE TITLE
Docs are not consistent with the docker-compose.yml

### ISSUE THREAD

**Issue by Atomzwieback** [RocketChat/Rocket.Chat.Metrics#6]
Currently im trying to bring this containers up and running and there by i noticed that the docs are not consistent with the docker-compose.yml in the point of the ports used by the grafana instance. In the docker-compose.yml there is port 3000 used and in the docs is the port 3300 used.

**Comment by frdmn** [comment]
Thanks @Atomzwieback! I just fixed this and added a note about possible port conflicts:

https://github.com/RocketChat/Rocket.Chat.Metrics/commit/71011be88004396328fd96bd847f6457035f2256
