### ISSUE TITLE
DDP USERS

### ISSUE THREAD

**Issue by LogiEx7** [RocketChat/Rocket.Chat.Metrics#8]
Hello, 

Can you tell me what the DDP Users panel is? And the panels available in DDP Rate Limiter.

Thank you in advance

**Comment by ankar84** [comment]
Yeah.
In general it would be sooo nice if there is was detailed information about all RC metrics and how to interpret them.

**Comment by frdmn** [comment]
The "DDP Users" are basically all connected and authenticated sessions established (including mobile clients, API, bots, etc.).

The "DDP Rate Limiter" shows data about rate limiter violations (in case you have them enabled in the admin UI → Rate Limiter → DDP Rate Limiter).

I'll currently working on a docs that'll explain each graph/value a bit more in detail.

**Comment by frdmn** [comment]
Docs can be found here: https://github.com/RocketChat/Rocket.Chat.Metrics/blob/master/metrics.md#ddp-users
